# Book settings
title: ICESat-2 Sea Ice Data Analysis and Visualization
author: Nicole Keeney
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url                       : https://github.com/nicolejkeeney/icesat2-book
  branch                    : master  
html:
  use_repository_button: true
launch_buttons:
  colab_url: "https://colab.research.google.com"

home_page_in_navbar: true 

html:
    extra_footer: |
        <div>
            [ICESat-2 mission](https://icesat-2.gsfc.nasa.gov/)
        </div>