# Book settings
title: ICESat-2 Sea Ice Thickness Data Analysis and Visualization
author: Nicole Keeney
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url                       : https://github.com/nicolejkeeney/icesat2-book
  branch                    : master  

html:
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true
  favicon                   : logo.png
  google_analytics_id       : "UA-177768395-1"

execute:
  allow_errors              : false
  exclude_patterns:
    - 'data_wrangling'
    - 'README.md'
    - 'LICENSE'


launch_buttons: 
  colab_url                 : https://colab.research.google.com

home_page_in_navbar: true 
