# Book settings
title: Sea Ice State Analysis
author: Nicole Keeney and Alek Petty
logo: figs/logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url                       : https://github.com/akpetty/icesat2-book
  branch                    : master  

html:
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true
  favicon                   : "figs/logo.png"
  google_analytics_id       : "G-J1HEQ5DMT0"


execute:
  execute_notebooks         : force
  allow_errors              : false
  timeout                   : 1000
  only_build_toc_files      : true
  exclude_patterns:
    - 'data_wrangling.ipynb'
    - 'delete/*'

launch_buttons: 
  binderhub_url: "https://mybinder.org"

home_page_in_navbar: true 
