# Book settings
title: ICESat-2 Sea Ice State Analysis
author: Nicole Keeney and Alek Petty
copyright: "2022"  # Copyright year to be placed in the footer
logo: content/figs/logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url                       : https://github.com/akpetty/icesat2-book
  branch                    : master  

html:
  use_repository_button     : true
  use_issues_button         : true
  use_edit_page_button      : true
  favicon                   : "content/figs/logo.png"
  google_analytics_id       : "G-J1HEQ5DMT0"
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer: Distributed under the MIT license


execute:
  execute_notebooks         : force
  allow_errors              : false
  timeout                   : 1000
  only_build_toc_files      : true
  exclude_patterns:
    - 'data_wrangling.ipynb'
    - 'delete/*'

launch_buttons: 
  binderhub_url: "https://mybinder.org"

home_page_in_navbar: true 
