name: icesat2_book

channels:
  - conda-forge
dependencies:
  - python=3.8
  - cartopy=0.18.0 
  - xarray
  - netcdf4
  - matplotlib 
  - pandas
  - numpy
  - scipy 
  - pip
  - pyproj
  - zarr 
  - dask
  - gcsfs=0.8.0
  - pip: 
    - jupyter
    - jupyter-book
    - gsutil
